
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://vets-service:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
            
 ---     
 spring:
   config:
     activate:
       on-profile: tls
server:
  ssl:
    key-alias: api-gateway-cert
    key-store-type: AzureKeyVault
    trust-store-type: AzureKeyVault
  port: 8443
azure:
  keyvault:
    uri: https://asa-mz-cqngc-eus-kv.vault.azure.net/
